### ISSUE TITLE
Stuck on pod install forever

### ISSUE THREAD

**Issue by hongfeiyang** [solid-software/flutter_vlc_player#143]
I was trying to use this package but it stuck at 'pod install' forever. I even tried to use this as a git repository and it still stuck at pod install forever.
```
dev_dependencies:
  shelf: ^0.7.9
  shelf_proxy: ^0.1.0+7
  flutter_vlc_player:
    git:
      url: https://github.com/solid-software/flutter_vlc_player.git
  flutter_test:
    sdk: flutter
```

I am using Xcode 11.3, macOS 10.14.6, Simulator iOS 13.3. pod version is 1.10.0
